### ISSUE TITLE
Data Preparation Notebook doesn't download MARDY data

### ISSUE THREAD

**Issue by 8W9aG** [DiegoLeon96/Neural-Speech-Dereverberation#1]
I noticed that when I run the [Generate_spectrograms](https://github.com/DiegoLeon96/Neural-Speech-Dereverberation/blob/main/data_generation/Generate_spectrograms.ipynb) notebook it fails because there are no files in the MARDY folder.

To fix this I added the following to the top of the notebook:
```
!sudo apt-get install unrar
!wget http://cspserver5.ee.ic.ac.uk/~sap/uploads/data/MARDY.rar
!mkdir data_espec
!mkdir data_espec/MARDY
!unrar e -y MARDY.rar data_espec/MARDY
```

**Comment by DiegoLeon96** [comment]
Thanks for your comment. It's true, I had MARDY (rar file) in Drive when I was working and I forgot to download it in colab.
